"""Add last_used fields to FoodReference

Revision ID: 1ecb5efd0441
Revises: ea3b94453a8b
Create Date: 2025-03-31 14:00:07.761370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecb5efd0441'
down_revision = 'ea3b94453a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable first
    op.add_column('food_reference', sa.Column('last_used_quantity', sa.Float(), nullable=True))
    op.add_column('food_reference', sa.Column('last_used_unit', sa.String(length=20), nullable=True))
    op.add_column('food_reference', sa.Column('last_used_meal_type', sa.String(length=20), nullable=True))
    
    # Step 2: Update existing rows with default values
    op.execute("UPDATE food_reference SET last_used_quantity = 100")
    op.execute("UPDATE food_reference SET last_used_meal_type = 'snack'")
    
    # Step 3: Alter column to make it non-nullable
    op.alter_column('food_reference', 'last_used_quantity',
               existing_type=sa.Float(),
               nullable=False,
               server_default='100')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_reference', 'last_used_meal_type')
    op.drop_column('food_reference', 'last_used_unit')
    op.drop_column('food_reference', 'last_used_quantity')
    # ### end Alembic commands ###
