"""Add weight_per_unit to FoodReference

Revision ID: 2d8641e327c2
Revises: 1ecb5efd0441
Create Date: 2025-03-31 14:18:53.904872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8641e327c2'
down_revision = '1ecb5efd0441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_per_unit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_reference', schema=None) as batch_op:
        batch_op.drop_column('weight_per_unit')

    # ### end Alembic commands ###
