"""Add sharing and creator fields to FoodReference

Revision ID: 7b9587795ba8
Revises: 
Create Date: 2025-03-30 20:58:56.653108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9587795ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('food_reference_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_reference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('food_reference_name_key', ['name'])
        batch_op.drop_column('creator_id')
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###
