"""Add brand and description to FoodEntry

Revision ID: bccef6a47300
Revises: 7b9587795ba8
Create Date: 2025-03-31 13:39:09.458096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccef6a47300'
down_revision = '7b9587795ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entry', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
