"""Add meal_type to FoodEntry

Revision ID: ea3b94453a8b
Revises: bccef6a47300
Create Date: 2025-03-31 13:41:53.665902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3b94453a8b'
down_revision = 'bccef6a47300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('food_entry', sa.Column('meal_type', sa.String(length=20), nullable=True))
    
    # Step 2: Set default value for existing rows
    op.execute("UPDATE food_entry SET meal_type = 'snack'")
    
    # Step 3: Make column non-nullable
    op.alter_column('food_entry', 'meal_type', nullable=False, existing_type=sa.String(length=20), 
                   existing_server_default=None, server_default="snack")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_entry', 'meal_type')
    # ### end Alembic commands ###
